"""Named endpoints: certificate handling and alias ownership.

The certificate tests run against a REAL certificate generated by openssl at
test time rather than a fixture blob, because the properties being checked —
wildcard scope, SAN-vs-CN precedence, expiry — are properties of X.509, and a
hand-written fixture would only prove the parser agrees with whoever wrote the
fixture.
"""

from __future__ import annotations

import shutil
import subprocess

import pytest

from app.services.endpoints import (
    ALIAS_RE,
    hostname_covered,
    normalise_aliases,
    parse_certificate,
)

pytestmark = pytest.mark.skipif(not shutil.which("openssl"), reason="needs openssl")


def make_cert(tmp_path, cn: str, sans: str | None) -> str:
    args = [
        "openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes",
        "-keyout", str(tmp_path / "k.pem"), "-out", str(tmp_path / "c.pem"),
        "-days", "30", "-subj", f"/CN={cn}",
    ]
    if sans:
        args += ["-addext", f"subjectAltName={sans}"]
    subprocess.run(args, check=True, capture_output=True)
    return (tmp_path / "c.pem").read_text()


# --- reading the certificate ---------------------------------------------

def test_reads_the_public_metadata(tmp_path):
    pem = make_cert(tmp_path, "llm.example.net", "DNS:llm.example.net")
    info = parse_certificate(pem)
    assert info.ok
    assert "llm.example.net" in (info.subject or "")
    assert info.sans == ["llm.example.net"]
    assert info.fingerprint_sha256 and len(info.fingerprint_sha256.split(":")) == 32
    assert info.not_after is not None
    assert 28 <= (info.days_remaining() or 0) <= 30


def test_a_bad_paste_is_reported_not_raised(tmp_path):
    """This runs on an upload path — a mangled paste must produce a message,
    not a 500."""
    for junk in ("", None, "not a cert", "-----BEGIN CERTIFICATE-----\ngarbage\n"):
        info = parse_certificate(junk)
        assert not info.ok
        assert info.error


def test_the_private_key_is_never_read(tmp_path):
    """CertInfo carries public fields only. If the key ever ended up on it, it
    would flow straight out through the API that exposes the metadata."""
    make_cert(tmp_path, "x.example.net", "DNS:x.example.net")
    key = (tmp_path / "k.pem").read_text()
    info = parse_certificate((tmp_path / "c.pem").read_text())
    blob = repr(vars(info))
    assert "PRIVATE KEY" not in blob
    assert key[:80] not in blob


# --- does the cert actually cover the hostname ---------------------------

def test_exact_san_match(tmp_path):
    info = parse_certificate(make_cert(tmp_path, "a.example.net", "DNS:a.example.net"))
    assert hostname_covered(info, "a.example.net")
    assert not hostname_covered(info, "b.example.net")


def test_a_wildcard_covers_exactly_one_label(tmp_path):
    """*.example.net covers a.example.net but NOT a.b.example.net. Getting this
    wrong would accept a cert that browsers then reject, and the operator would
    find out from a TLS warning after a promotion."""
    info = parse_certificate(make_cert(tmp_path, "w", "DNS:*.example.net"))
    assert hostname_covered(info, "a.example.net")
    assert not hostname_covered(info, "a.b.example.net")
    assert not hostname_covered(info, "example.net")


def test_sans_win_over_the_common_name(tmp_path):
    """A certificate WITH SANs is defined by them — browsers ignore the CN. If
    we fell back to the CN we would accept a cert that does not actually serve
    the hostname."""
    info = parse_certificate(
        make_cert(tmp_path, "llm.example.net", "DNS:other.example.net")
    )
    assert info.sans == ["other.example.net"]
    assert not hostname_covered(info, "llm.example.net")


def test_the_common_name_is_used_only_when_there_is_no_san(tmp_path):
    info = parse_certificate(make_cert(tmp_path, "legacy.example.net", None))
    assert info.sans == []
    assert hostname_covered(info, "legacy.example.net")


def test_an_unrelated_hostname_is_never_covered(tmp_path):
    info = parse_certificate(make_cert(tmp_path, "a.example.net", "DNS:*.example.net"))
    assert not hostname_covered(info, "evil.com")
    assert not hostname_covered(info, "")


# --- aliases --------------------------------------------------------------

def test_accepts_the_aliases_actually_in_use():
    """Including the slash form — `deepseek-ai/DeepSeek-V4-Flash` is a real
    alias, so the pattern must not be tightened to exclude it."""
    ok, bad = normalise_aliases([
        "DSV4-W4A16-FP8", "deepseek-ai/DeepSeek-V4-Flash",
        "deepseek-v4-flash", "DSV4-DSpark",
    ])
    assert len(ok) == 4 and not bad


def test_reads_the_legacy_space_separated_form():
    """So an existing instance's served_model_names moves onto an endpoint
    unchanged."""
    ok, _ = normalise_aliases("DSV4-DSpark  deepseek-v4-flash\nDSV4-W4A16-FP8")
    assert ok == ["DSV4-DSpark", "deepseek-v4-flash", "DSV4-W4A16-FP8"]


def test_order_is_preserved_and_duplicates_collapse():
    """Order reaches the vLLM --served-model-name flag, so it is not free to
    reorder; the first occurrence wins."""
    ok, _ = normalise_aliases(["b", "a", "b", "c"])
    assert ok == ["b", "a", "c"]


@pytest.mark.parametrize("bad", ["has space", "semi;colon", "quote'", "back`tick", "--flag", "a" * 200])
def test_rejects_anything_that_would_need_quoting(bad):
    ok, rejected = normalise_aliases([bad])
    assert bad.split()[0] not in ok or not ALIAS_RE.match(bad)
    assert rejected or " " in bad


def test_rejected_entries_are_reported_not_silently_dropped():
    ok, rejected = normalise_aliases(["good-one", "bad!"])
    assert ok == ["good-one"]
    assert rejected == ["bad!"]


def test_none_and_junk_do_not_raise():
    assert normalise_aliases(None) == ([], [])
    assert normalise_aliases(123)[1]


# --- the schema property that makes this worth doing ---------------------

def test_an_alias_is_unique_across_endpoints():
    """The entire point. An alias owned by exactly one endpoint cannot be
    ambiguous, which is the class of bug that silently routed production
    traffic to an arbitrary instance."""
    from app.models import EndpointAlias

    assert EndpointAlias.__table__.columns["alias"].unique is True


def test_membership_and_the_pointer_are_separate_columns():
    """Collapsing them makes promotion unrepresentable: a candidate is not
    `current` when it starts, so it would launch WITHOUT the production
    aliases, and flipping a pointer afterwards cannot add them to an
    already-running vLLM — --served-model-name is baked in at launch."""
    from app.models import Endpoint, Instance

    assert "endpoint_id" in Instance.__table__.columns          # membership
    assert "current_instance_id" in Endpoint.__table__.columns  # the pointer
    # One instance hosts at most one nginx sidecar, so at most one endpoint.
    assert Endpoint.__table__.columns["current_instance_id"].unique is True


def test_promotion_history_survives_instance_deletion():
    """History must outlive what it describes — deleting an instance must not
    erase the record of it having served production."""
    from app.models import EndpointPromotion

    cols = EndpointPromotion.__table__.columns
    assert cols["to_instance_name"].nullable is False   # snapshot, not a FK read
    assert cols["to_instance_id"].nullable is True      # FK goes NULL on delete
    assert "actor" in cols                              # ready for RBAC
